# name: New RPM 
# on:
#   push:
#     branches: [ "testing" ]
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# env:
#   ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
# jobs:
#   build:
#     runs-on: self-hosted    
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3
#         with:
#           token: ${{ secrets.GHCR_TOKEN }}
#           ssh-key: ${{ secrets.CHECK_AGENT_ACCESS }}
      
#       - name: Update repo data
#         run: |
#           sudo yum install -y createrepo
#           createrepo x86_64/
#           createrepo aarch64/
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git commit -a -m "[GITHUB ACTION] Updated Repo Data"
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           token: ${{ secrets.GHCR_TOKEN }}
#           ssh-key: ${{ secrets.CHECK_AGENT_ACCESS }}
  
name: Red Hat Workflow

on:
  push:
    branches:
      - testing  # Adjust this to match your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for compatibility

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GHCR_TOKEN }}
        ssh-key: ${{ secrets.CHECK_AGENT_ACCESS }}

    - name: Set up Docker
      run: docker pull centos:8
      shell: bash

    - name: Run createrepo in Docker
      run: |
        docker run -v ${{ github.workspace }}:/workspace centos:8 /bin/bash -c "sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && dnf install -y createrepo && createrepo /workspace/x86_64/ && createrepo /workspace/aarch64/"
      shell: bash

    - name: Update repo data
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git commit -a -m "[GITHUB ACTION] Updated Repo Data"


    - name: Push changes
      run: git push origin master