name: New RPM Workflow

on:
  push:
    branches:
      - testing# Adjust this to match your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for compatibility

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GHCR_TOKEN }}
        ssh-key: ${{ secrets.CHECK_AGENT_ACCESS }}

    - name: Set up Docker
      run: docker pull centos:8
      shell: bash

    - name: Run createrepo in Docker
      run: |
        docker run -v ${{ github.workspace }}:/workspace centos:8 /bin/bash -c "sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && dnf install -y createrepo && createrepo /workspace/x86_64/ && createrepo /workspace/aarch64/"
      shell: bash

    - name: Update repo data
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git commit -a -m "[GITHUB ACTION] Updated Repo Data"
        git push origin 
